name: CI

on:
  push:
    # Run on the main branch
    branches:
      - main
    # Releases are tags named 'v<version>', and must have the "major.minor.micro", for example: "0.1.0".
    # Release candidates are tagged as `v<version>-rc<num>`, for example: "0.1.0-rc1".
    tags:
      - "v*"
  # Also on PRs, just be careful not to publish anything
  pull_request:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test

      - name: Formatting
        run: cargo fmt --check

  examples:
    needs: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        example: ["embassy", "blocking", "tokio", "nrf52"]
    steps:
      - name: Build
        run: pushd examples/${{ matrix.example }}; cargo build; popd
